language: php

sudo: true

php:
  - 7.2
  - 7.3
  - hhvm

env:
  global:
    - DRIVER=pdo
    - SPHINXSEARCH_BUILD=rel22
    - SPHINX_PORT=9307
  matrix:
    - USE_LARAVEL_VERSION=6.0
    - USE_LARAVEL_VERSION=7.0

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_install:
  - mkdir $HOME/manticore
  - pushd $HOME/manticore
  - wget -O manticore.deb --quiet https://github.com/manticoresoftware/manticoresearch/releases/download/3.3.0/manticore_3.3.0-200204-01fc8ad1-release.`lsb_release -cs`_amd64-bin.deb
  - dpkg -x manticore.deb .
  - popd

install:
  - composer require "illuminate/bus:^${USE_LARAVEL_VERSION}"
  - composer install --prefer-dist
  - $HOME/sphinx/usr/bin/searchd -c tests/fixtures/sphinx.conf

script:
  - ./vendor/bin/phpunit --coverage-text

notifications:
  email: false
