language: php

sudo: true

php:
  - 7.2
  - 7.3

env:
  global:
    - DRIVER=pdo
    - SPHINX_PORT=9306
  matrix:
    - USE_LARAVEL_VERSION=6.0
    - USE_LARAVEL_VERSION=7.0

matrix:
  fast_finish: true

before_install:
  - mkdir $HOME/manticore
  - pushd $HOME/manticore
  - wget -O manticore.deb --quiet https://github.com/manticoresoftware/manticoresearch/releases/download/3.4.0/manticore_3.4.0-200326-0686d9f-release.xenial_amd64-bin.deb
  - dpkg -x manticore.deb .
  - popd

install:
  - $HOME/manticore/usr/bin/searchd -c tests/fixtures/sphinx.conf
  - composer require "illuminate/bus:^${USE_LARAVEL_VERSION}"
  - composer install --prefer-dist

script:
  - ./vendor/bin/phpunit --coverage-text

notifications:
  email: false
